version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_calendar
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: calendar
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
